---
name: check images

on:
  pull_request:
  push:   # runs on every push
  workflow_dispatch:

jobs:
  check_images:
    name: check images
    runs-on: ubuntu-latest
    container:
      image: perl@sha256:1ec7df9b6c70e31b05d937f929ddfe06a6a1966d98c09ae78ecfbb391a364739
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: check images
        run: ./scripts/check_images.sh
